### ISSUE TITLE
Document all used environment variables

### ISSUE THREAD

**Issue by marcingrzejszczak** [zdharma/zshelldoc#5]
I don't know if that's even possible but it would be awesome for each function to print what env vars it's using. Also it would be great if when we're doing `export ...` to provide some documentation on what those env vars mean. WDYT about this, is it even possible to be considered?

**Comment by psprint** [comment]
Looks somewhat difficult, but on other hand, I would have to save every `local`/`typeset`/`declare`/`export`, then track every assignment checking that it doesn't reference to `local`, if it doesn't then create a file in `data/` subdirectory, per-function/script-body, with name of the variable referenced. Then in `zsd-to-adoc` add some indicators on env variables. Maybe only variables that have `export` should be tracked and reported. It seems that something should be possible, it might be not perfect but still useful. Could a $3 donation be granted for this? I would sit to this today. Sorry for the requests, it's just that I code much and am within coffee spiral, drink much of it and not daily-working. In anyway I should approach this task at some point.

**Comment by marcingrzejszczak** [comment]
Done. Enjoy your coffee.

**Comment by psprint** [comment]
Thanks! I wonder what will come up from this.

**Comment by psprint** [comment]
Here is how this feature looks like:

![env_feat_demo](https://user-images.githubusercontent.com/6049288/43221984-e503dab4-904e-11e8-86b5-d82ceab31edb.png)

I need to do fine-tuning so that bash unconventional variable uses like `${var?value}` are detected, not ignored, otherwise it should be somewhat complete. I limited the code to "export" builtin. In zsh one can export by `typeset -gx VAR` but I think that regular script-work means using `export`, and that global variables aren't that important (if only global, not exported).

**Comment by marcingrzejszczak** [comment]
Looks great!
